---
title: "Supplementary"
output: 
  html_document:
    toc: true
    toc_float:
      smooth_scroll: FALSE
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(boot)
library(dplyr)
library(flavipack)
library(furrr)
library(lubridate)
library(purrr)
library(readr)
library(readxl)
library(stringr)
library(tidyr)

source("./R_scripts/cohort_utils.R")
source("./R_scripts/CPC.R")
source("./R_scripts/DGP.R")
source("./R_scripts/follow_up.R")
source("./R_scripts/KFCS.R")
source("./R_scripts/NMC.R")
source("./R_scripts/plots.R")
```

# S1 - All pairs

```{r S1_chunk}
plot_S1()

ggsave("./plots/suppl/S1.png", width = 5, height = 3)
```

# S3 - Correlation PRNT vs HAI

```{r S3_chunk}
plot_S3()

ggsave("./plots/suppl/S3.png", width = 5, height = 3)
```

# S4 - Distribution of rises

```{r S4_chunk}
plot_S4()

ggsave("./plots/suppl/S4.png", height = 3, width = 3)
```

# S5 - Sensitivity on decay rates by serotype

```{r S5_chunk}
plot_S5()

ggsave("./plots/suppl/S5.png", height = 3, width = 5)
```

# S6 - Sensitivity on threshold

```{r S6_chunk}
plot_S6()

ggsave("./plots/suppl/S6.png", width = 5, height = 3)
```

# S7 - Imputing on titres below LOD

```{r S7_chunk}
plot_S7()

ggsave("./plots/suppl/S7.png", width = 5, height = 3)
```

# S8 - Alternative scenarios (infection patterns)

```{r S8_chunk, fig.width = 5, fig.height = 3}
plot_list_S8_S9 <- plot_S8_S9()

plot_list_S8_S9[[1]]

ggsave("./plots/suppl/S8.png", width = 5, height = 3)
```

# S9 - Alternative scenarios (population titres)

```{r S9_chunk, fig.width = 5, fig.height = 3}
plot_list_S8_S9[[2]]

ggsave("./plots/suppl/S9.png", width = 5, height = 3)
```

# S10 - OAS

```{r S10_chunk, fig.height = 4, fig.width = 4}
plot_list <- plot_S10_S11()

plot_list[[1]]

ggsave("./plots/suppl/S9.png", height = 4, width = 4)
```

# S11- OAS Seronegatives

```{r S11_chunk, fig.height = 4, fig.width = 4}
plot_list[[2]]

ggsave("./plots/suppl/S10.png", height = 4, width = 4)
```

# S12 - Asymptotic probability of infection

```{r S12_chunk, fig.width = 5, fig.height = 3}
plot_S12()

ggsave("./plots/suppl/S12.png", width = 5, height = 3)
ggsave("./plots/suppl/S12.pdf", width = 5, height = 3)
```



